---
- name: Update Packages
  hosts: all
  become: true
  vars_files: ["../vars.yaml"]

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist
